### ISSUE TITLE
运行出问题

### ISSUE THREAD

**Issue by vonking** [cycz/jdBuyMask#22]
Traceback (most recent call last):
  File "C:\Users\*****\Desktop\Python\jdBuyMask-master_V2\jdBuyMask-master\jdBuyMask_V2.py", line 14, in <module>
    from config.config import global_config
  File "C:\Users\*****\Desktop\Python\jdBuyMask-master_V2\jdBuyMask-master\config\config.py", line 23, in <module>
    global_config = Config()
  File "C:\Users\*****\Desktop\Python\jdBuyMask-master_V2\jdBuyMask-master\config\config.py", line 10, in __init__
    raise FileNotFoundError("No such file: config.ini")
FileNotFoundError: No such file: config.ini
-----
请教为什么会报这样的错？我的配置哪里出了问题吗

**Comment by cexll** [comment]
No such file: config.ini 提示得很清楚了...找不到config.ini 你看一下路径

**Comment by mem4tgo** [comment]
> No such file: config.ini 提示得很清楚了...找不到config.ini 你看一下路径

原来双击就可以啊。我还每次CMD  python  XXX
所以找不到

**Comment by mem4tgo** [comment]
楼主直接双击PY

**Comment by cexll** [comment]
麻烦问题解决了就把这个iss关掉
