### ISSUE TITLE
目前下订单时遇到的bug

### ISSUE THREAD

**Issue by xingkongzyx** [cycz/jdBuyMask#25]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jdBuyMask_V2.py", line 493, in <module>
    sendMail(mail, skuidUrl, False)
  File "C:\Users\.....\Desktop\jdBuyMask-master\jdemail\jdEmail.py", line 35, in sendMail
    server = smtplib.SMTP_SSL(host=smtp_server)
  File "C:\Users\.....\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 1031, in __init__
    source_address)
  File "C:\Users\.....\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Users\.....\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\.....\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 1037, in _get_socket
    self.source_address)
  File "C:\Users\.....\AppData\Local\Programs\Python\Python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
KeyboardInterrupt

**Comment by lxdzh** [comment]
一样提示
Traceback (most recent call last):
  File "jdBuyMask_V2.py", line 493, in <module>
    sendMail(mail, skuidUrl, False)
  File "F:\idmxz\jdBuyMask-master_3\jdBuyMask-master\jdemail\jdEmail.py", line 38, in sendMail
    server.login(from_addr, password)
  File "D:\py\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "D:\py\lib\smtplib.py", line 635, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "D:\py\lib\smtplib.py", line 425, in docmd
    return self.getreply()
  File "D:\py\lib\smtplib.py", line 391, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "D:\py\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\py\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\py\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

**Comment by macahaha** [comment]
确实下单有问题，会提示获取订单信息失败。。

**Comment by zimo0825** [comment]
我下单也有问题
2020-02-07 14:19:38,984 ERROR: 60323904322 添加到购物车失败
2020-02-07 14:19:39,868 ERROR: 下单页面数据解析异常：list index out of range
Traceback (most recent call last):
  File "E:/学习/python/口罩/2020.02.06/jdBuyMask-master/jdBuyMask_V2.py", line 489, in <module>
    if buyMask(skuId):
  File "E:/学习/python/口罩/2020.02.06/jdBuyMask-master/jdBuyMask_V2.py", line 423, in buyMask
    risk_control = get_checkout_page_detail()
  File "E:/学习/python/口罩/2020.02.06/jdBuyMask-master/jdBuyMask_V2.py", line 291, in get_checkout_page_detail
    return risk_control
UnboundLocalError: local variable 'risk_control' referenced before assignment

**Comment by HuanYuanHe** [comment]
有个情况就是如果商品下架,但是商家设置还有剩余库存,就会导致添加购物车失败, 提示risk_control

**Comment by JohnsonLiu1985** [comment]
如何修改关键词，比如：检测到第[1]个口罩都无货，这里的口罩如何修改？如何跟随ID名自动修改？
