### ISSUE TITLE
一直往微信发送成功信息，但其实并没有下单成功

### ISSUE THREAD

**Issue by messiisgod** [cycz/jdBuyMask#31]
2020-02-07 16:59:24,568 INFO: 第1次 
2020-02-07 16:59:25,133 INFO: [35]个skuid口罩无货
2020-02-07 16:59:25,516 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:25.134857]]
2020-02-07 16:59:26,018 INFO: 第2次 
2020-02-07 16:59:26,561 INFO: [35]个skuid口罩无货
2020-02-07 16:59:26,881 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:26.562301]]
2020-02-07 16:59:27,682 INFO: 第3次 
2020-02-07 16:59:27,977 INFO: [35]个skuid口罩无货
2020-02-07 16:59:28,274 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:27.977558]]
2020-02-07 16:59:29,075 INFO: 第4次 
2020-02-07 16:59:29,327 INFO: [35]个skuid口罩无货
2020-02-07 16:59:29,664 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:29.328333]]

**Comment by cycz** [comment]
> 2020-02-07 16:59:24,568 INFO: 第1次
> 2020-02-07 16:59:25,133 INFO: [35]个skuid口罩无货
> 2020-02-07 16:59:25,516 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:25.134857]]
> 2020-02-07 16:59:26,018 INFO: 第2次
> 2020-02-07 16:59:26,561 INFO: [35]个skuid口罩无货
> 2020-02-07 16:59:26,881 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:26.562301]]
> 2020-02-07 16:59:27,682 INFO: 第3次
> 2020-02-07 16:59:27,977 INFO: [35]个skuid口罩无货
> 2020-02-07 16:59:28,274 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:27.977558]]
> 2020-02-07 16:59:29,075 INFO: 第4次
> 2020-02-07 16:59:29,327 INFO: [35]个skuid口罩无货
> 2020-02-07 16:59:29,664 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:29.328333]]

不好意思 测试代码没删完

**Comment by 13211222** [comment]
一样啊

**Comment by canacer** [comment]
> > 2020-02-07 16:59:24,568 INFO: 第1次
> > 2020-02-07 16:59:25,133 INFO: [35]个skuid口罩无货
> > 2020-02-07 16:59:25,516 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:25.134857]]
> > 2020-02-07 16:59:26,018 INFO: 第2次
> > 2020-02-07 16:59:26,561 INFO: [35]个skuid口罩无货
> > 2020-02-07 16:59:26,881 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:26.562301]]
> > 2020-02-07 16:59:27,682 INFO: 第3次
> > 2020-02-07 16:59:27,977 INFO: [35]个skuid口罩无货
> > 2020-02-07 16:59:28,274 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:27.977558]]
> > 2020-02-07 16:59:29,075 INFO: 第4次
> > 2020-02-07 16:59:29,327 INFO: [35]个skuid口罩无货
> > 2020-02-07 16:59:29,664 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:29.328333]]
> 
> 不好意思 测试代码没删完

020-02-07 17:36:02,595 INFO: [2293339]类型口罩有货啦!马上下单
2020-02-07 17:36:02,595 INFO: 第[1/3]次尝试提交订单
2020-02-07 17:36:02,892 INFO: 购物车信息：{'2293339': {'name': '三得利（Suntory） 无糖乌龙茶饮料  500ml*15瓶整箱装', 'verder_id': '8888', 'count': 1, 'unit_price': '29.90', 'total_price': '29.90', 'is_selected': False, 'p_type': '13', 'target_id': '50073142629', 'promo_id': '50073142629'}}
2020-02-07 17:36:02,892 INFO: 2293339 已在购物车中，调整数量为 1
2020-02-07 17:36:03,506 INFO: 下单信息：{'address': '陕西 ', 'receiver': '*** 1****3355', 'total_price': '29.90', 'items': []}
Traceback (most recent call last):
2020-02-07 17:36:03,692 INFO: 订单提交成功! 订单号：109442457724
  File "C:/Users/Administrator/Desktop/jdBuyMask-master/jdBuyMask_V2.py", line 502, in <module>
    message.send(skuidUrl, True)
  File "C:\Users\Administrator\Desktop\jdBuyMask-master\message\message.py", line 28, in send
    msg = desp + ' 类型口罩，下单失败了，快去抢购！'
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

删完测试代码以后 下单成功也不会进行方糖微信推送了

**Comment by messiisgod** [comment]
> > 2020-02-07 16:59:24,568 INFO: 第1次
> > 2020-02-07 16:59:25,133 INFO: [35]个skuid口罩无货
> > 2020-02-07 16:59:25,516 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:25.134857]]
> > 2020-02-07 16:59:26,018 INFO: 第2次
> > 2020-02-07 16:59:26,561 INFO: [35]个skuid口罩无货
> > 2020-02-07 16:59:26,881 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:26.562301]]
> > 2020-02-07 16:59:27,682 INFO: 第3次
> > 2020-02-07 16:59:27,977 INFO: [35]个skuid口罩无货
> > 2020-02-07 16:59:28,274 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:27.977558]]
> > 2020-02-07 16:59:29,075 INFO: 第4次
> > 2020-02-07 16:59:29,327 INFO: [35]个skuid口罩无货
> > 2020-02-07 16:59:29,664 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:29.328333]]
> 
> 不好意思 测试代码没删完

OK完美解决，辛苦了

**Comment by messiisgod** [comment]
> > > 2020-02-07 16:59:24,568 INFO: 第1次
> > > 2020-02-07 16:59:25,133 INFO: [35]个skuid口罩无货
> > > 2020-02-07 16:59:25,516 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:25.134857]]
> > > 2020-02-07 16:59:26,018 INFO: 第2次
> > > 2020-02-07 16:59:26,561 INFO: [35]个skuid口罩无货
> > > 2020-02-07 16:59:26,881 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:26.562301]]
> > > 2020-02-07 16:59:27,682 INFO: 第3次
> > > 2020-02-07 16:59:27,977 INFO: [35]个skuid口罩无货
> > > 2020-02-07 16:59:28,274 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:27.977558]]
> > > 2020-02-07 16:59:29,075 INFO: 第4次
> > > 2020-02-07 16:59:29,327 INFO: [35]个skuid口罩无货
> > > 2020-02-07 16:59:29,664 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/ 类型口罩，已经下单了。24小时内付款 [2020-02-07 16:59:29.328333]]
> > 
> > 
> > 不好意思 测试代码没删完
> 
> 020-02-07 17:36:02,595 INFO: [2293339]类型口罩有货啦!马上下单
> 2020-02-07 17:36:02,595 INFO: 第[1/3]次尝试提交订单
> 2020-02-07 17:36:02,892 INFO: 购物车信息：{'2293339': {'name': '三得利（Suntory） 无糖乌龙茶饮料 500ml_15瓶整箱装', 'verder_id': '8888', 'count': 1, 'unit_price': '29.90', 'total_price': '29.90', 'is_selected': False, 'p_type': '13', 'target_id': '50073142629', 'promo_id': '50073142629'}} 2020-02-07 17:36:02,892 INFO: 2293339 已在购物车中，调整数量为 1 2020-02-07 17:36:03,506 INFO: 下单信息：{'address': '陕西 ', 'receiver': '_** 1****3355', 'total_price': '29.90', 'items': []}
> Traceback (most recent call last):
> 2020-02-07 17:36:03,692 INFO: 订单提交成功! 订单号：109442457724
> File "C:/Users/Administrator/Desktop/jdBuyMask-master/jdBuyMask_V2.py", line 502, in
> message.send(skuidUrl, True)
> File "C:\Users\Administrator\Desktop\jdBuyMask-master\message\message.py", line 28, in send
> msg = desp + ' 类型口罩，下单失败了，快去抢购！'
> TypeError: unsupported operand type(s) for +: 'bool' and 'str'
> 
> 删完测试代码以后 下单成功也不会进行方糖微信推送了

下载新版本

**Comment by 13211222** [comment]
Traceback (most recent call last):
  File "C:\Users\10749\Desktop\jdBuyMask-master\jdBuyMask_V2.py", line 493, in <module>
    if item_removed(skuId):
  File "C:\Users\10749\Desktop\jdBuyMask-master\jdBuyMask_V2.py", line 396, in item_removed
    page = requests.get(url=url, headers=headers)
  File "C:\Users\10749\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\10749\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\10749\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\10749\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\10749\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\10749\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
能帮我看一下提示这个是什么问题吗
