### ISSUE TITLE
目前的比较严重的bug

### ISSUE THREAD

**Issue by xingkongzyx** [cycz/jdBuyMask#35]
2020-02-07 20:08:36,766 INFO: [25411367334]类型口罩有货，但已下柜商品
2020-02-07 20:08:36,907 INFO: [3621679]类型口罩有货，但已下柜商品
2020-02-07 20:08:38,408 INFO: 第2次
2020-02-07 20:08:38,465 INFO: [21]个skuid口罩无货
2020-02-07 20:08:38,630 INFO: [1038227]类型口罩有货啦!马上下单
2020-02-07 20:08:38,952 INFO: 购物车信息：{'1038227': {'name': '蓝月亮 消毒水 漂白 除菌84消毒液600g/瓶 杀菌率99.999% 消毒杀菌更放心 家庭和公共场所消毒', 'verder_id': '8888', 'count': 1, 'unit_price': '7.80', 'to
tal_price': '7.80', 'is_selected': False, 'p_type': '13', 'target_id': '50072147434', 'promo_id': '50072147434'}}
2020-02-07 20:08:38,952 INFO: 1038227 已在购物车中，调整数量为 1
Status: 503, Url: http://passport.jd.com/new/login.aspx?ReturnUrl=https%3A%2F%2Ftrade.jd.com%2Fshopping%2Forder%2FgetOrderInfo.action%3Frid%3D1581077319029
2020-02-07 20:08:39,073 ERROR: 获取订单结算页信息失败
Traceback (most recent call last):
  File "D:\jdBuyMask-master\message\jdEmail.py", line 37, in sendMail
    server.sendmail(from_addr, to_addr, msg.as_string())
  File "C:\Users\Yuxuan Zhu\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 867, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (554, b'MI:STC 163 smtp1,GdxpCgDXIy1FUz1e59reBg--.144S2 1581077317,601,please see http://mail.163.com/help/help_spam_16.htm?ip=......&hostid=smtp1&time=1581077317', 'jdbuymask@163.com')

**Comment by wwwlwr** [comment]
v2没碰到另外一个老哥打包exe的v4我碰到了这个问题

**Comment by antoychan** [comment]
> 2020-02-07 20:08:36,766 INFO: [25411367334]类型口罩有货，但已下柜商品
> 2020-02-07 20:08:36,907 INFO: [3621679]类型口罩有货，但已下柜商品
> 2020-02-07 20:08:38,408 INFO: 第2次
> 2020-02-07 20:08:38,465 INFO: [21]个skuid口罩无货
> 2020-02-07 20:08:38,630 INFO: [1038227]类型口罩有货啦!马上下单
> 2020-02-07 20:08:38,952 INFO: 购物车信息：{'1038227': {'name': '蓝月亮 消毒水 漂白 除菌84消毒液600g/瓶 杀菌率99.999% 消毒杀菌更放心 家庭和公共场所消毒', 'verder_id': '8888', 'count': 1, 'unit_price': '7.80', 'to
> tal_price': '7.80', 'is_selected': False, 'p_type': '13', 'target_id': '50072147434', 'promo_id': '50072147434'}}
> 2020-02-07 20:08:38,952 INFO: 1038227 已在购物车中，调整数量为 1
> Status: 503, Url: http://passport.jd.com/new/login.aspx?ReturnUrl=https%3A%2F%2Ftrade.jd.com%2Fshopping%2Forder%2FgetOrderInfo.action%3Frid%3D1581077319029
> 2020-02-07 20:08:39,073 ERROR: 获取订单结算页信息失败
> Traceback (most recent call last):
> File "D:\jdBuyMask-master\message\jdEmail.py", line 37, in sendMail
> server.sendmail(from_addr, to_addr, msg.as_string())
> File "C:\Users\Yuxuan Zhu\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 867, in sendmail
> raise SMTPSenderRefused(code, resp, from_addr)
> smtplib.SMTPSenderRefused: (554, b'MI:STC 163 smtp1,GdxpCgDXIy1FUz1e59reBg--.144S2 1581077317,601,please see http://mail.163.com/help/help_spam_16.htm?ip=......&hostid=smtp1&time=1581077317', '[jdbuymask@163.com](mailto:jdbuymask@163.com)')

老铁，我也遇到跟你一样的问题，请问你的 问题解决了吗？

**Comment by antoychan** [comment]
2020-02-08 21:29:24,574 INFO: [60323904322]类型口罩有货啦!马上下单
2020-02-08 21:29:25,164 INFO: 购物车信息：{'7080686': {'name': '威刚（ADATA）DDR4 2666 8GB 台式机内存 万紫千红', 'verder_id': '8888', 'count': 1, 'unit_price': '299.00', 'total_price': '299.00', 'is_selected': False, 'p_type': '13', 'target_id': '50067179503', 'promo_id': '50067179503'}, '598827': {'name': '九州风神（DEEPCOOL） 玄冰400 CPU散热器（多平台/支持AM4/4热管/智能温控/发蓝光/12CM风扇/附带硅脂）', 'verder_id': '8888', 'count': 1, 'unit_price': '89.90', 'total_price': '89.90', 'is_selected': False, 'p_type': '13', 'target_id': '50067576582', 'promo_id': '50067576582'}}
2020-02-08 21:29:25,378 ERROR: 60323904322 添加到购物车失败
2020-02-08 21:29:26,021 INFO: Message sent successfully [text: 京东商品监控, desp: https://item.jd.com/60323904322.html 类型口罩，下单失败了，快去抢购！ [2020-02-08 21:29:25.780122]]
