### ISSUE TITLE
添加购物车失败

### ISSUE THREAD

**Issue by zjfjiayou** [cycz/jdBuyMask#4]
2020-02-05 13:01:56,324 ERROR: 4642656 添加到购物车失败
2020-02-05 13:01:57,016 ERROR: 下单页面数据解析异常：list index out of range
Traceback (most recent call last):
  File "./jdBuyMask.py", line 493, in <module>
    if buyMask(skuId):
  File "./jdBuyMask.py", line 459, in buyMask
    risk_control = get_checkout_page_detail()
  File "./jdBuyMask.py", line 345, in get_checkout_page_detail
    return risk_control
UnboundLocalError: local variable 'risk_control' referenced before assignment

**Comment by zjfjiayou** [comment]
环境是用的docker
dockerfile
FROM python:3
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD [ "python", "./jdBuyMask.py" ]

执行命令
docker build -t jd .
docker run -it --rm --name running-jd jd

**Comment by cycz** [comment]
刚提交了个代码。你试下，看看是不是商品的问题

**Comment by zjfjiayou** [comment]
好的，稍等

**Comment by zjfjiayou** [comment]
非常感觉，谢谢小哥，已赞

**Comment by Newcomer365** [comment]
源码里有你京东COOKIES信息

**Comment by zbwujie** [comment]
我也碰到了怎么解决呢

**Comment by zbwujie** [comment]
Traceback (most recent call last):
  File "C:/Users/Masha/Downloads/Compressed/jdBuyMask-master_3/jdBuyMask-master/jdBuyMask.py", line 510, in <module>
    if buyMask(skuId):
  File "C:/Users/Masha/Downloads/Compressed/jdBuyMask-master_3/jdBuyMask-master/jdBuyMask.py", line 475, in buyMask
    risk_control = get_checkout_page_detail()
  File "C:/Users/Masha/Downloads/Compressed/jdBuyMask-master_3/jdBuyMask-master/jdBuyMask.py", line 348, in get_checkout_page_detail
    return risk_control
UnboundLocalError: local variable 'risk_control' referenced before assignment

**Comment by cycz** [comment]
> Traceback (most recent call last):
> File "C:/Users/Masha/Downloads/Compressed/jdBuyMask-master_3/jdBuyMask-master/jdBuyMask.py", line 510, in 
> if buyMask(skuId):
> File "C:/Users/Masha/Downloads/Compressed/jdBuyMask-master_3/jdBuyMask-master/jdBuyMask.py", line 475, in buyMask
> risk_control = get_checkout_page_detail()
> File "C:/Users/Masha/Downloads/Compressed/jdBuyMask-master_3/jdBuyMask-master/jdBuyMask.py", line 348, in get_checkout_page_detail
> return risk_control
> UnboundLocalError: local variable 'risk_control' referenced before assignment

刚刚有个版本有点问题，还是不行的话加我qq

**Comment by zbwujie** [comment]
您好请问您qq是多少

**Comment by cycz** [comment]
> 您好请问您qq是多少

838143144
