### ISSUE TITLE
V2版本极速模式，商品ID里有下架商品，会报错

### ISSUE THREAD

**Issue by haiyangzhijia** [cycz/jdBuyMask#44]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jdBuyMask-master\jdBuyMask-master\jdBuyMask_V2.py", line 622, in fastMode
    fastModeAutoBuy(inStockSkuid)
  File "C:\Users\Administrator\Desktop\jdBuyMask-master\jdBuyMask-master\jdBuyMask_V2.py", line 568, in fastModeAutoBuy
    if fastModeBuyMask(skuId):
  File "C:\Users\Administrator\Desktop\jdBuyMask-master\jdBuyMask-master\jdBuyMask_V2.py", line 454, in fastModeBuyMask
    risk_control = get_checkout_page_detail()
  File "C:\Users\Administrator\Desktop\jdBuyMask-master\jdBuyMask-master\jdBuyMask_V2.py", line 304, in get_checkout_page_detail
    return risk_control
UnboundLocalError: local variable 'risk_control' referenced before assignment

**Comment by cycz** [comment]
好的 我测试一下
