### ISSUE TITLE
亲爱的用户，您刷新过于频繁，请稍后再试

### ISSUE THREAD

**Issue by yxrs89** [cycz/jdBuyMask#49]
Traceback (most recent call last):
  File "/Users/xiaoliwei/PycharmProjects/jdBuyMask/jdBuyMask_V2.py", line 365, in submit_order
    resp_json = json.loads(resp.text)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

把resp.text打印出来，显示是“亲爱的用户，您刷新过于频繁，请稍后再试。。。”的html页面，请问如何解决？谢谢！

**Comment by cycz** [comment]
是不是商品有异常 已经下柜等情况， 去掉这个商品吧

**Comment by yxrs89** [comment]
不是的哦~我一共就一个商品而且特地找了个有货的试下单的，而且我换了很多商品都是。我试了下V2、V3、V4版本都报这个。是不是我本地设置的问题呢？我看可以加入购物车成功，就是提交订单时候报这个。

**Comment by undefinedcodezhong** [comment]
我也是,特意搜了个有货的商品做测试,一直没成功,卡在: "ERROR: 订单结算页面获取异常：Exceeded 30 redirects."
请问有什么建议吗?
