### ISSUE TITLE
2.10号版本，v2正常模式报错

### ISSUE THREAD

**Issue by haiyangzhijia** [cycz/jdBuyMask#56]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jdBuyMask-master\jdBuyMask-master\jdBuyMask_V2.py", line 490, in normalMode
    inStockSkuid = check_stock()
TypeError: check_stock() missing 3 required positional arguments: 'checksession', 'skuids', and 'area'

**Comment by onlylhf** [comment]
可以将 490行修改成

`inStockSkuid = check_stock(checksession, skuids, area)`

**Comment by Feb17** [comment]
D:\jdBuyMask-master>python jdBuyMask_V2.py
Traceback (most recent call last):
  File "jdBuyMask_V2.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

请教下这是什么原因导致的？

**Comment by onlylhf** [comment]
> D:\jdBuyMask-master>python jdBuyMask_V2.py
> Traceback (most recent call last):
> File "jdBuyMask_V2.py", line 7, in
> import requests
> ModuleNotFoundError: No module named 'requests'
> 
> 请教下这是什么原因导致的？

安装这个内容进行安装依赖: [https://blog.csdn.net/cyz52/article/details/104239558#_38](https://blog.csdn.net/cyz52/article/details/104239558#_38)

还有要新建一个提问的,不要在别人问题下问其他问题.

**Comment by Feb17** [comment]
> > D:\jdBuyMask-master>python jdBuyMask_V2.py
> > Traceback (most recent call last):
> > File "jdBuyMask_V2.py", line 7, in
> > import requests
> > ModuleNotFoundError: No module named 'requests'
> > 请教下这是什么原因导致的？
> 
> 安装这个内容进行安装依赖: https://blog.csdn.net/cyz52/article/details/104239558#_38
> 
> 还有要新建一个提问的,不要在别人问题下问其他问题.

感谢，收到！
