### ISSUE TITLE
exe version and V3 version both error '订单结算页面获取异常'

### ISSUE THREAD

**Issue by lipeng12138** [cycz/jdBuyMask#82]
用一个有货商品测试，报错如下:
当前是V3版本
2020-02-19 12:09:30,840 INFO: 登录成功
2020-02-19 12:09:31,038 INFO: 登录账号名称***
2020-02-19 12:09:31,418 INFO: 清空购物车
2020-02-19 12:09:31,858 INFO: 33256902525  已成功加入购物车
2020-02-19 12:09:31,859 INFO: 第1次
2020-02-19 12:09:32,108 INFO: 检测[1]个口罩有货，[0]个口罩无货，[0]个口罩下柜，耗时[249]ms
2020-02-19 12:09:32,110 INFO: [33256902525]类型口罩有货啦!马上下单
2020-02-19 12:09:34,671 ERROR: 订单结算页面获取异常：HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D1781EE9B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\jdBuyMask-master\jdEmail.py", line 35, in sendMail
    server.login(from_addr, password)
  File "D:\Anaconda\lib\smtplib.py", line 694, in login
    self.ehlo_or_helo_if_needed()
  File "D:\Anaconda\lib\smtplib.py", line 603, in ehlo_or_helo_if_needed
    raise SMTPHeloError(code, resp)
smtplib.SMTPHeloError: (500, b'Error: bad syntax')

V3版本和exe版本都这样报了错，不清楚问题出在哪

**Comment by cycz** [comment]
京东国际的商品还待测试
